server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  #sprig cloud config 连接github的配置
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ToAlive/microservicecloud-config.git #git仓库的地址