server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #只有一个eureka服务注册中心,只用在一个服务注册中心注册
      defaultZone: http://eureka7001.com:7001/eureka/
      #eureka集群，需要在每个eureka服务注册中心注册这个服务
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  #指定在服务注册中心显示的主机名，默认是localhost:microservicecloud-dept8001
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true     #访问路径可以显示IP地址

#将这些属性返回到info页面上去
info:
  app.name: WhoamI9527
  company.name: WhoamI
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}


zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: microservicecloud-dept # "*" 表示忽略所有的微服务实例名
  prefix: /WhoamI
